M48
; DRILL file KiCad 10.0.5 date 2026-09-23T15:55:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-23T15:55:58+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X47.11Y-6.605
X52.89Y-6.605
T2
X5.0Y-5.0
X5.0Y-95.0
X95.0Y-5.0
X95.0Y-95.0
M30
